version: "3"

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - ./clickhouse/data/:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    expose:
      - 9009
# -------------FLINK------------------
  jobmanager:
    image: apache/flink:1.13.1-scala_2.12-java8
    command: "jobmanager.sh start-foreground"
    ports:
      - 8081:8081
    volumes:
      - ./flink/jobmanager/conf:/opt/flink/conf
      - ./flink/jobmanager/flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - ./flink/jobmanager/flink-savepoints-directory:/tmp/flink-savepoints-directory
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      
  taskmanager:
    image: apache/flink:1.13.1-scala_2.12-java8
    depends_on:
      - jobmanager
    command: "taskmanager.sh start-foreground"
    volumes:
      - ./flink/taskmanager/conf:/opt/flink/conf
      - ./flink/taskmanager/flink-checkpoints-directory:/tmp/flink-checkpoints-directory
      - ./flink/taskmanager/flink-savepoints-directory:/tmp/flink-savepoints-directory
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  
# -------------KAFKA------------------
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "input:2:1, output:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
      - 9094:9094

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6